# Generated by Django 4.2 on 2023-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact', models.CharField(max_length=200, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=200, verbose_name='Confirm Password')),
            ],
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='artworkcart',
            name='price',
        ),
        migrations.AlterField(
            model_name='privateevent',
            name='contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contact number'),
        ),
    ]
